media:
- name: images
  label: Media
  input: src/media
  output: /src/media
- name: blogImages
  label: Blog Images
  input: src/media/blog
  output: /src/media/blog
  extensions: [jpg, png, jpeg, webp, avif]
- name: pageImages
  label: Page Images
  input: src/media/pages
  output: /src/media/pages
  extensions: [jpg, png, jpeg, webp, avif]
- name: files
  label: Files
  input: src/files
  output: files
  categories: [ document ]

# reusable groups of fields
components:

  authors: # a reference field for selecting author(s) from the authors content type
    type: reference
    required: false
    options:
      collection: authors
      multiple: true
      label: "{fields.name}"
      search: "name"
  
  meta: # an object for setting metadata on content
    type: object
    fields:
      - name: title
        label: Content Title
        type: string
      - name: description
        label: Content Description
        type: text
        options:
          rows: 2
      - name: featuredImage
        label: Featured Image
        type: object
        fields:
        - name: image
          label: Image
          type: image
          options:
            media: blogImages
            extensions: [png, jpg, jpeg]
        - name: alt
          label: Alt text
          description: This should be an accurate description of the image for assistive technologies. It can be left blank for images that are purely decorative
          type: string

  contentDate: # an object for setting publication and update dates on content
    type: object
    label: Publication Date
    fields:
      - name: pubDate
        label: Published date
        type: date
      - name: updatedAt
        label: Updated at
        type: date

  infoSection: # an object for adding a Hero section to a page
    label: Info Sections
    type: object
    fields:
      - name: sections
        label: Add another section
        component: infoBlockObject


  infoBlockObject:
    type: object
    list:
      collapsible:
        collapsed: true # Default collapsed state
        summary: "{fields.title}"
    fields:
    # Each item defines a possible block structure the user can select.
      # These typically use 'component' or define 'fields' directly.
      - name: title
        type: string
        label: Section Title
      - name: description
        type: string
        label: Section Description
      - name: image
        component: standardImage
        label: Section Image
      - name: links
        label: Section Link
        component: links


  infoBlock:
    type: block
    list:
      collapsible:
        collapsed: true # Default collapsed state
    blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
    blocks:
    # Each item defines a possible block structure the user can select.
      # These typically use 'component' or define 'fields' directly.
      - name: sectionTitle
        label: Info section
        fields:
        - name: title
          type: string
          label: Title
        - name: sectionLinks
          label: Link(s)
          component: links


    
  links: # a block for adding an array different types of links (eg: reference and URL)
    type: block
    list:
      collapsible:
        collapsed: true # Default collapsed state
        summary: "{fields.label}"
    blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
    blocks:
    # Each item defines a possible block structure the user can select.
      # These typically use 'component' or define 'fields' directly.
      - name: pageRef
        label: Page link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: reference
            options:
              collection: blog
              label: "{meta.title}"
              search: "meta.title,name"
      - name: postRef
        label: Post link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: reference
            options:
              collection: blog
              label: "{meta.title}"
              search: "meta.title,name"
      - name: archiveRef
        label: List page link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: reference
            options:
              collection: blog
              label: "{meta.title}"
              search: "meta.title,name"
      - name: urlLink
        label: URL link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: string
            pattern:
              regex: '^^https://\w+(\.\w+)+.*$'
              message: 'Must be a valid URL eg: starts with https:// [does not need to have www]'
      - name: email
        label: Email address
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Email
            type: string
            pattern:
              regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
              message: 'This must be a valid email address'
  
  standardImage: # an object for adding an image with alt text
    label: Image
    type: object
    fields:
    - name: image
      label: Image
      type: image
      options:
        media: blogImages
    - name: alt
      label: Alt text
      description: Alt text should be an accurate description of the image for assistive technologies
      type: string

  featuredImage: # an object for adding an image with customisable field options
    label: Featured Image
    type: object
    fields:
    - name: image
      label: Image
      type: image
      options:
        media: pageImages
    - name: alt
      label: Alt text
      description: Alt text should be an accurate description of the image for assistive technologies
      type: string
    - name: caption
      label: Caption
      description: Optional
      type: string
    - name: variant
      label: Variant
      description: Choose the variant; 'rounded' adds a border radius and shadow
      type: select
      default: plain
      options:
        values: [ rounded, plain ]
    - name: layout
      label: Layout
      description: Choose the layout; 'grid' places the image and caption horizontally
      type: select
      default: default
      options:
        values: [ default, grid ]
        
  bodyText: # a object for adding a simple rich text field ( w/ media disabled)
    label: Content block
    type: object
    fields:
      - name: content
        label: Rich text
        type: rich-text
        options:
          media: false
          
  hero: # an object for adding a Hero section to a page
    label: Hero Section
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: heroImage
        label: Cover Image
        type: object
        fields:
          - name: image
            type: image
          - name: altText
            label: Alt text
            type: string
      - name: heroLinks
        label: Link(s)
        component: links


content:
  - name: archives
    label: Archive pages
    type: collection
    path: src/data/archives
    filename: '{primary}.md'
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: meta
        label: Metadata
        component: meta
      - name: body
        label: Introduction
        type: rich-text
        options:
          media: false
      - name: settings
        label: Page settings
        type: object
        fields:
          - name: postsPerPage
            label: Posts per page
            type: number
          - name: layout
            label: Page layout
            type: select
            options:
              values: [ grid, column ]

  - name: page
    label: Pages
    path: src/data/pages
    type: collection
    filename: '{primary}.md'
    view:
      fields: [ meta.title ]
      primary: meta.title
      sort: [ meta.title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: isPublished
        label: Published
        type: boolean
      - name: meta
        label: Content overview
        component: meta
      - name: authors
        label: Authors
        component: authors
      - name: relatedContent
        label: Related content
        description: Any links selected here will be shown in the page sidebar
        component: links
      - name: body
        type: rich-text
      - name: contentBlocks
        label: Content blocks
        type: block
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "Block - {index}"
        blockKey: __typename
        blocks:
          - name: postHero
            component: hero
          - name: body
            component: bodyText
          - name: infoBlock
            component: infoSection
            
  - name: blog
    label: Blog
    path: src/data/blog
    type: collection
    filename: '{primary}.md'
    view:
      fields: [ title, dates.pubDate, isPublished ]
      primary: title
      sort: [ title, dates.pubDate ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: isPublished
        label: Published
        type: boolean
      - name: dates
        component: contentDate
      - name: meta
        label: Content overview
        component: meta
      - name: authors
        label: Authors
        component: authors
      - name: title
        label: Title
        type: string
      - name: body
        type: rich-text
      - name: contentBlocks
        label: Content blocks
        type: block
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "Block - {index}"
        blockKey: __typename
        blocks:
          - name: postHero
            component: hero
          - name: body
            component: bodyText
          - name: infoBlock
            component: infoSection

      # ... fields defined here ...
  - name: authors
    label: Authors
    path: src/data/authors
    filename: '{primary}.md'
    type: collection
    view:
      fields: [name]
      primary: name
    fields:
      - name: name
        label: Name
        type: string
      - name: bio
        label: Biography
        type: text
      - name: featuredImage
        label: Photograph
        type: object
        fields:
        - name: image
          label: Image
          type: image
          options:
            path: src/media/authors
            extensions: [jpeg, jpg, png, webp, avif]
        - name: alt
          label: Alt text
          type: string
      - name: contact
        label: Contact options
        type: object
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "{fields.label}"
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: string
  - name: globalSettings
    label: Site Configuration
    type: file
    path: src/settings/global.json
    fields:
      - name: site
        label: Site Metadata
        component: meta
      - name: navigation
        type: object
        label: Main menu
        fields:
          - name: menuLinks
            label: Primary navigation
            component: links
     