media:
- name: images
  label: Media
  input: src/media
  output: /src/media
- name: blogImages
  label: Blog Images
  input: src/media/blog
  output: /src/media/blog
  extensions: [jpg, png, jpeg]
- name: files
  label: Files
  input: src/files
  output: files
  categories: [ document ]

content:
  - name: blog
    label: Blog
    path: src/data/blog
    type: collection
    filename: '{primary}.md'
    view:
      fields: [ title, pubDate ]
      primary: title
      sort: [ title, pubDate ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: isDraft
        label: Draft
        type: boolean
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: featuredImage
        label: Featured Image
        type: object
        fields:
        - name: image
          label: Image
          type: image
          options:
            media: blogImages
            extensions: [png, jpg, jpeg]
        - name: alt
          label: Alt text
          description: Alt text should be an accurate description of the image for assistive technologies
          type: string
        - name: caption
          label: Caption
          description: Optional
          type: string
        - name: variant
          label: Variant
          description: Choose the variant; 'rounded' adds a border radius and shadow
          type: select
          default: plain
          options:
            values: [ rounded, plain ]
        - name: layout
          label: Layout
          description: Choose the layout; 'grid' places the image and caption horizontally
          type: select
          default: default
          options:
            values: [ default, grid ]
      - name: authors
        label: Authors
        type: reference
        required: false
        options:
          collection: authors
          multiple: true
          search: "name"
      - name: pubDate
        label: Published date
        type: date
      - name: updatedAt
        label: Updated at
        type: date
      - name: body
        label: Body
        type: rich-text
        options:
          path: src/media/blog
      # ... fields defined here ...
  - name: authors
    label: Authors
    path: src/data/authors
    filename: '{primary}.md'
    type: collection
    view:
      fields: [name]
      primary: name
    fields:
      - name: name
        label: Name
        type: string
      - name: bio
        label: Biography
        type: text
      - name: featuredImage
        label: Featured Image
        type: object
        fields:
        - name: image
          label: Image
          type: image
          options:
            path: src/media/authors
            extensions: [jpeg, jpg, png, webp, avif]
        - name: alt
          label: Alt text
          type: string
      - name: contact
        label: Contact options
        type: object
        list:
          collapsible:
            collapsed: false # Default collapsed state
        fields:
          - name: link
            label: Link
            type: string
          - name: label
            label: Label
            type: string
  - name: globalSettings
    label: Site settings
    type: file
    path: src/settings/global.json
    fields:
      - name: siteName
        label: Site name
        type: string
      