media:
- name: images
  input: src/media
  output: media
- name: files
  label: Files
  input: src/files
  output: files
  categories: [ document ]

content:
  - name: blog
    label: Blog
    path: src/data/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: isDraft
        label: Draft
        type: boolean
      - name: authors
        label: Authors
        type: reference
        required: false
        options:
          collection: authors
          multiple: true
          search: "name"
          value: "{id}"
          label: "{name} - Author"
      - name: body
        label: Body
        type: rich-text
      # ... fields defined here ...
  - name: authors
    label: Authors
    path: src/data/authors
    filename: '{primary}.md'
    type: collection
    view:
      fields: [name]
      primary: name
    fields:
      - name: name
        label: Name
        type: string
      - name: bio
        label: Biography
        type: text