media:
- name: images
  label: Media
  input: src/data/blog
  output: /data/blog
- name: files
  label: Files
  input: src/files
  output: files
  categories: [ document ]

content:
  - name: blog
    label: Blog
    path: src/data/blog
    type: collection
    filename: 'index.md'
    view:
      fields: [ title, pubDate ]
      primary: title
      sort: [ title, pubDate ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: featuredImage
        label: Featured Image
        type: object
        fields:
        - name: image
          label: Image
          type: image
          options:
            input: src/data/blog
            output: src/data/blog
            extensions: [jpeg, jpg, png, webp, avif]
        - name: alt
          label: Alt text
          type: string
      - name: authors
        label: Authors
        type: reference
        required: false
        options:
          collection: authors
          multiple: true
          search: "name"
      - name: pubDate
        label: Published date
        type: date
      - name: updatedAt
        label: Updated at
        type: date
      - name: isDraft
        label: Draft
        type: boolean
      - name: body
        label: Body
        type: rich-text
        options:
          path: src/media/blog
      # ... fields defined here ...
  - name: authors
    label: Authors
    path: src/data/authors
    filename: '{primary}.md'
    type: collection
    view:
      fields: [name]
      primary: name
    fields:
      - name: name
        label: Name
        type: string
      - name: bio
        label: Biography
        type: text
      - name: featuredImage
        label: Featured Image
        type: object
        fields:
        - name: image
          label: Image
          type: image
          options:
            path: src/media/authors
            extensions: [jpeg, jpg, png, webp, avif]
        - name: alt
          label: Alt text
          type: string
      - name: contact
        label: Contact options
        type: object
        list:
          collapsible:
            collapsed: false # Default collapsed state
        fields:
          - name: link
            label: Link
            type: string
          - name: label
            label: Label
            type: string