media:
- name: images
  label: Media
  input: src/media
  output: /src/media
- name: blogImages
  label: Blog Images
  input: src/media/blog
  output: /src/media/blog
  extensions: [jpg, png, jpeg, webp, avif]
- name: pageImages
  label: Page Images
  input: src/media/pages
  output: /src/media/pages
  extensions: [jpg, png, jpeg, webp, avif]
- name: files
  label: Files
  input: src/files
  output: files
  categories: [ document ]

# reusable groups of fields
components:

  authors: # a reference field for selecting author(s) from the authors content type
    type: reference
    required: false
    options:
      collection: authors
      multiple: true
      label: "{fields.name}"
      search: "name"
  
  meta: # utility for setting metadata on content
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        description: This should be no more than 170 characters and will be used by search engines to identify the content of a page. This description may also be used on some archive pages.
        type: text
        options:
          rows: 2
      - name: featuredImage
        label: Featured Image
        description: This image will be used by search engines and on social media platforms when sharing this content. The image may also be used on some archive pages.
        component: standardImage

  contentDate: # utility component for setting publication and update dates on content
    type: object
    label: Publication Date
    fields:
      - name: pubDate
        label: Published date
        type: date
      - name: updatedAt
        label: Updated at
        type: date

  repeaterBlockObject: # utility layout component used to add repeating sections to block compontents
    type: object
    list:
      collapsible:
        collapsed: true # Default collapsed state
        summary: "{fields.title}"
    fields:
    # Each item defines a possible block structure the user can select.
      # These typically use 'component' or define 'fields' directly.
      - name: title
        type: string
        label: Section Title
      - name: description
        type: text
        label: Section Description
        options:
          rows: 5
      - name: image
        component: standardImage
        label: Section Image
      - name: links
        label: Section Link
        component: links

  repeaterImageObject: # utility layout component used to add repeating sections to block compontents
    type: object
    list:
      collapsible:
        collapsed: true # Default collapsed state
        summary: "Image {index}"
    fields:
    # Each item defines a possible block structure the user can select.
      # These typically use 'component' or define 'fields' directly.
      - name: image
        component: featuredImage
        label: Image

  links: # a utility component for adding an array different types of links (eg: reference and URL)
    type: block
    list:
      collapsible:
        collapsed: true # Default collapsed state
        summary: "{fields.label}"
    blockKey: type # Optional: customize the key used to store the block name, defaults to `_block`
    blocks:
    # Each item defines a possible block structure the user can select.
      # These typically use 'component' or define 'fields' directly.
      - name: pageRef
        label: Page link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: reference
            options:
              collection: blog
              label: "{meta.title}"
              search: "meta.title,name"
      - name: postRef
        label: Post link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: reference
            options:
              collection: blog
              label: "{meta.title}"
              search: "meta.title,name"
      - name: archiveRef
        label: List page link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: reference
            options:
              collection: blog
              label: "{meta.title}"
              search: "meta.title,name"
      - name: urlLink
        label: URL link
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: string
            pattern:
              regex: '^^https://\w+(\.\w+)+.*$'
              message: 'Must be a valid URL eg: starts with https:// [does not need to have www]'
      - name: email
        label: Email address
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Email
            type: string
            pattern:
              regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
              message: 'This must be a valid email address'
  
  standardImage: # an object for adding an image with alt text
    label: Image
    type: object
    fields:
    - name: image
      label: Image
      type: image
      options:
        media: images
    - name: alt
      label: Alt text
      description: Alt text should be an accurate description of the image for assistive technologies
      type: string

  featuredImage: # an object for adding an image with alt text and caption fields
    label: Featured Image
    type: object
    fields:
    - name: image
      label: Image
      type: image
      options:
        media: images
    - name: alt
      label: Alt text
      description: Alt text should be an accurate description of the image for assistive technologies. This is not shown visually
      type: string
    - name: caption
      label: Caption (optional)
      description: If a caption is set, this will be shown under the image
      type: string
        
  bodyText: # a utility component for adding a simple rich text field ( w/ media disabled)
    label: Content block
    type: object
    fields:
      - name: content
        label: Rich text
        type: rich-text
        options:
          media: false

  cta: # an object for adding a Hero section to a page
    label: CTA
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
        options:
          rows: 5
      - name: image
        label: Image
        component: standardImage
      - name: links
        label: Link(s)
        component: links
        
  hero: # an object for adding a Hero section to a page
    label: Hero Section
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
        options:
          rows: 5
      - name: image
        label: Image
        component: standardImage
      - name: links
        label: Link(s)
        component: links

  faqs: # an object for adding a FAQs component with repeating sections to a page
    label: FAQs
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
        options:
          rows: 5
      - name: sections
        label: Add section
        component: repeaterBlockObject

  imageGallery: # an object for adding an image gallery component to a page
    label: Image(s)
    type: object
    fields:
      - name: image
        label: Add image
        component: repeaterImageObject
        
  infoSection: # an object for adding an info component with repeating sections to a page
    label: Info Sections
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
        options:
          rows: 5
      - name: sections
        label: Add section
        component: repeaterBlockObject

  tabs: # an object for adding a tabs component with repeating sections to a page
    label: Tabs
    type: object
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
        options:
          rows: 5
      - name: sections
        label: Add section
        component: repeaterBlockObject

content:
  - name: archive
    label: Archive pages
    type: collection
    path: src/data/archives
    filename: '{primary}.json'
    view:
      fields: [ meta.title ]
      primary: meta.title
      sort: [ meta.title ]
      default:
        search: ''
        sort: meta.title
        order: desc
    fields:
      - name: meta
        label: Content overview
        component: meta
      - name: body
        label: Page content
        type: rich-text
        options:
          media: false
      - name: settings
        label: Page settings
        type: object
        fields:
          - name: postsPerPage
            label: Content items per page
            type: number
          - name: layout
            label: Page layout
            type: select
            options:
              values: [ grid, column ]

  - name: page
    label: Pages
    path: src/data/pages
    type: collection
    filename: '{primary}.md'
    view:
      fields: [ meta.title, isPublished ]
      primary: meta.title
      sort: [ meta.title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: isPublished
        label: Published
        type: boolean
      - name: meta
        label: Content overview
        component: meta
      - name: relatedContent
        label: Related Links
        description: Any links selected here will be shown in the page sidebar
        component: links
      - name: contentBlocks
        label: Content blocks
        type: block
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "Block - {index}"
        blockKey: __typename
        blocks:
          - name: hero
            component: hero
          - name: richText
            component: bodyText
          - name: faqs
            component: faqs
          - name: imageGallery
            component: imageGallery
          - name: infoBlock
            component: infoSection
          - name: tabs
            component: tabs

  - name: article
    label: Articles
    path: src/data/articles
    type: collection
    format: json-frontmatter
    filename: '{primary}.json'
    view:
      fields: [ meta.title, isPublished ]
      primary: meta.title
      sort: [ meta.title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: isPublished
        label: Published
        type: boolean
      - name: meta
        label: Content overview
        component: meta
      - name: relatedContent
        label: Related Links
        description: Any links selected here will be shown in the page sidebar
        component: links
      - name: contentBlocks
        label: Content blocks
        type: block
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "Block - {index}"
        blockKey: __typename
        blocks:
          - name: hero
            component: hero
          - name: richText
            component: bodyText
          - name: faqs
            component: faqs
          - name: imageGallery
            component: imageGallery
          - name: infoBlock
            component: infoSection
          - name: tabs
            component: tabs
            
  - name: blog
    label: Blog
    path: src/data/blog
    type: collection
    filename: '{primary}.json'
    view:
      fields: [ meta.title, dates.pubDate, isPublished ]
      primary: meta.title
      sort: [ meta.title, dates.pubDate ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: isPublished
        label: Published
        description: Use this to control whether a content item is published to the front-end of the website
        type: boolean
      - name: dates
        component: contentDate
      - name: meta
        label: Content overview 
        component: meta
      - name: authors
        label: Authors
        component: authors
      - name: contentBlocks
        label: Content blocks
        type: block
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "Block - {index}"
        blockKey: __typename
        blocks:
          - name: postHero
            component: hero
          - name: richText
            component: bodyText
          - name: faqs
            component: faqs
          - name: infoBlock
            component: infoSection
          - name: tabs
            component: tabs
      # ... fields defined here ...
  - name: author
    label: Authors
    path: src/data/authors
    filename: '{primary}.json'
    type: collection
    view:
      fields: [name]
      primary: name
    fields:
      - name: name
        label: Name
        type: string
      - name: bio
        label: Biography
        type: text
      - name: featuredImage
        label: Photograph
        component: standardImage
      - name: contact
        label: Contact options
        type: object
        list:
          collapsible:
            collapsed: true # Default collapsed state
            summary: "{fields.label}"
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: string
            
  - name: globalSettings
    label: Site Configuration
    type: file
    path: src/settings/global.json
    fields:
      - name: site
        label: Site Metadata
        component: meta
      - name: navigation
        type: object
        label: Main menu
        fields:
          - name: menuLinks
            label: Primary navigation
            component: links
     